"""change-two

Revision ID: 405f4e1f9b0e
Revises: 592d0d0bb410
Create Date: 2021-10-30 13:06:38.966000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '405f4e1f9b0e'
down_revision = '592d0d0bb410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='student')
    op.drop_table('student')
    op.drop_table('teacher_experiment')
    op.drop_table('student_course')
    op.drop_table('student_examquestion')
    op.drop_table('course')
    op.drop_table('admin')
    op.drop_table('student_assginment')
    op.drop_table('teacher_class')
    op.drop_index('email', table_name='teacher')
    op.drop_table('teacher')
    op.drop_table('question')
    op.drop_table('teacher_course')
    op.drop_table('experiment_file')
    op.drop_table('exam')
    op.drop_table('assignment')
    op.drop_table('teacher_exam')
    op.drop_table('student_class')
    op.drop_table('experiment')
    op.drop_table('student_experiment')
    op.drop_table('course_file')
    op.drop_table('class')
    op.drop_table('exam_question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_question',
    sa.Column('eq_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('exam_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.exam_id'], name='exam_question_ibfk_1'),
    sa.ForeignKeyConstraint(['question_id'], ['question.question_id'], name='exam_question_ibfk_2'),
    sa.PrimaryKeyConstraint('eq_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('class',
    sa.Column('class_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('class_name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('s_number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('class_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('course_file',
    sa.Column('course_file_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_id', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('file_name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('size', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], name='course_file_ibfk_1'),
    sa.PrimaryKeyConstraint('course_file_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('student_experiment',
    sa.Column('experiment_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('t_id', mysql.VARCHAR(length=5), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.experiment_id'], name='student_experiment_ibfk_1'),
    sa.ForeignKeyConstraint(['t_id'], ['teacher.t_id'], name='student_experiment_ibfk_2'),
    sa.PrimaryKeyConstraint('experiment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('experiment',
    sa.Column('experiment_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('experiment_title', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('experiment_brief', mysql.VARCHAR(length=8192), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('end_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('experiment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('student_class',
    sa.Column('class_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('s_id', mysql.VARCHAR(length=7), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], name='student_class_ibfk_1'),
    sa.ForeignKeyConstraint(['s_id'], ['student.s_id'], name='student_class_ibfk_2'),
    sa.PrimaryKeyConstraint('class_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('teacher_exam',
    sa.Column('exam_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('t_id', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('assignment_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.assignment_id'], name='teacher_exam_ibfk_3'),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.exam_id'], name='teacher_exam_ibfk_1'),
    sa.ForeignKeyConstraint(['t_id'], ['teacher.t_id'], name='teacher_exam_ibfk_2'),
    sa.PrimaryKeyConstraint('exam_id', 'assignment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('assignment',
    sa.Column('assignment_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_id', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('assignment_title', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('assignment_content', mysql.VARCHAR(length=4096), nullable=True),
    sa.Column('change_time', mysql.DATETIME(), nullable=True),
    sa.Column('end_time', mysql.DATETIME(), nullable=True),
    sa.Column('weight', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], name='assignment_ibfk_1'),
    sa.PrimaryKeyConstraint('assignment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('exam',
    sa.Column('exam_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('start_time', mysql.DATETIME(), nullable=True),
    sa.Column('end_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('exam_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('experiment_file',
    sa.Column('experiment_file_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('experiment_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('size', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.experiment_id'], name='experiment_file_ibfk_1'),
    sa.PrimaryKeyConstraint('experiment_file_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('teacher_course',
    sa.Column('course_id', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('t_id', mysql.VARCHAR(length=5), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], name='teacher_course_ibfk_1'),
    sa.ForeignKeyConstraint(['t_id'], ['teacher.t_id'], name='teacher_course_ibfk_2'),
    sa.PrimaryKeyConstraint('course_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('question',
    sa.Column('question_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('option_a', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('option_b', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('option_c', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('option_d', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('answer', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experiment_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', mysql.VARCHAR(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.experiment_id'], name='question_ibfk_1'),
    sa.PrimaryKeyConstraint('question_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('teacher',
    sa.Column('t_id', mysql.VARCHAR(length=5), nullable=False),
    sa.Column('t_pwd', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('is_active', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('department', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('t_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('email', 'teacher', ['email'], unique=False)
    op.create_table('teacher_class',
    sa.Column('class_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('t_id', mysql.VARCHAR(length=5), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], name='teacher_class_ibfk_1'),
    sa.ForeignKeyConstraint(['t_id'], ['teacher.t_id'], name='teacher_class_ibfk_2'),
    sa.PrimaryKeyConstraint('class_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('student_assginment',
    sa.Column('s_id', mysql.VARCHAR(length=7), nullable=False),
    sa.Column('assignment_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.assignment_id'], name='student_assginment_ibfk_2'),
    sa.ForeignKeyConstraint(['s_id'], ['student.s_id'], name='student_assginment_ibfk_1'),
    sa.PrimaryKeyConstraint('s_id', 'assignment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('admin',
    sa.Column('admin_id', mysql.VARCHAR(length=5), nullable=False),
    sa.Column('admin_pwd', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('state', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('course',
    sa.Column('course_id', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('course_name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('course_type', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cover', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('course_state', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('change_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('course_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('student_examquestion',
    sa.Column('eq_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('s_id', mysql.VARCHAR(length=7), nullable=True),
    sa.Column('spare_time', mysql.DATETIME(), nullable=True),
    sa.Column('is_correct', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['eq_id'], ['exam_question.eq_id'], name='student_examquestion_ibfk_1'),
    sa.ForeignKeyConstraint(['s_id'], ['student.s_id'], name='student_examquestion_ibfk_2'),
    sa.PrimaryKeyConstraint('eq_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('student_course',
    sa.Column('course_id', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('s_id', mysql.VARCHAR(length=7), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], name='student_course_ibfk_1'),
    sa.ForeignKeyConstraint(['s_id'], ['student.s_id'], name='student_course_ibfk_2'),
    sa.PrimaryKeyConstraint('course_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('teacher_experiment',
    sa.Column('experiment_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('t_id', mysql.VARCHAR(length=5), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.experiment_id'], name='teacher_experiment_ibfk_1'),
    sa.ForeignKeyConstraint(['t_id'], ['teacher.t_id'], name='teacher_experiment_ibfk_2'),
    sa.PrimaryKeyConstraint('experiment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('student',
    sa.Column('s_id', mysql.VARCHAR(length=7), nullable=False),
    sa.Column('s_pwd', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('is_active', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('department', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('s_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('email', 'student', ['email'], unique=False)
    # ### end Alembic commands ###
