"""initial migration

Revision ID: e478215dc95f
Revises: 
Create Date: 2021-11-08 14:07:58.210635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e478215dc95f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'student', ['email'])
    op.create_unique_constraint(None, 'teacher', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher', type_='unique')
    op.drop_constraint(None, 'student', type_='unique')
    # ### end Alembic commands ###
